### PR TITLE
Rebuild v4.18.0

### PR DESCRIPTION
**Pull request by ELundby45**
# Rebuild v4.18.0

[huggingface_hub-feedstock](https://github.com/AnacondaRecipes/huggingface_hub-feedstock) was updated and a change was introduced preventing building the existing `transformers-feedstock`. This rebuild pins `huggingface_hub` to the previous version to prevent the following error: 

`ImportError: cannot import name ‘login’ from ‘huggingface_hub.hf_api’`

Offending PR: https://github.com/huggingface/huggingface_hub/pull/1041/files

### CODE REVIEW

**Review by psteyer — APPROVED** [review]
LGTM

**Review by varlackc — COMMENTED** [review]
It seems that there is a redirect on the `doc_url`:
doc_url: https://huggingface.co/docs/transformers/index

**Review by skupr-anaconda — APPROVED** [review]
